# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf39dec8fe2e3d93568319f7338a7081cc145f1a5556fb08b9fb46c6b511f0812f1fe6a6f9287bed3155ddd8ccd5cb1daa54aaed3f1a7589c418764c6c075359

test:
  secret_key_base: a733213ac7f54cb5fa01dff2a009f043fd07180184bc2de1b864fd8edd1cf099e348d68c78e2583387931dead27f54a307ab1863272f1a4974b62b0e4c3edffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
